### ISSUE TITLE
스트리밍 시청 시 주기적으로 중단되는 현상

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/mosainfo-mobile-app#6]
## 오류 설명
아래의 에러와 함께 스트리밍 (out 을 보는 유저쪽) 이 자꾸 중지됨

[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

**Comment by hanslelee** [comment]
## 참고
https://github.com/flutter/flutter/issues/75112

**Comment by hanslelee** [comment]
## + 추가 에러 및 정보
스트리밍을 시청하다가 시청자쪽에서 다음 에러가 발생하는 것을 확인했습니다.
`Thread 32: EXC_BAD_ACCESS (code=1, address=0x30)`

구글링해보니 다음과 같은 글을 발견하였습니다.
> Hey @ralienpp, I've been suffering from the same issue. But in the end, I understood why this was happening. I think it is while the model is running, there is not enough memory for it to use. So the device can not allocate anymore. In my case, I was using my model with 512 * 512 image sizes. After I realized the issue, it started to work for 128 * 128 . So currently, I am trying to do is to enable GPU delegate (which does not seem to work :/ ) and maybe quantize my model.

https://github.com/am15h/tflite_flutter_plugin/issues/189

어떻게 하는 게 좋을까요...? 화질을 낮춰도 종료되는지 한번 같이 테스트해보면 좋을 것 같습니다😭

**Comment by hanslelee** [comment]
## 오류 해결
ffmpeg에서 프리셋을 veryfast로 바꾸었더니 해결되었다. ([참고](https://m.blog.naver.com/josm17/220601051707))
```    
command = ['ffmpeg',
           '-y',
           '-f', 'rawvideo',
           '-vcodec', 'rawvideo',
           '-pix_fmt', 'bgr24',
           '-s', "{}x{}".format(width, height),
           '-r', str(fps),
           '-i', '-',
           '-c:v', 'libx264',
           '-pix_fmt', 'yuv420p',
           '-preset', 'veryfast',
           '-f', 'flv',
           rtmp_out_url]
```
