### ISSUE TITLE
스트리밍 종료시 시청자들에게 이를 알리기 위한 방법

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/mosainfo-mobile-app#7]
## 오류 설명
live/out 주소에서 더이상 스트리밍되고있지 않을 때 아래의 로그가 뜨는듯 함

[NULL @ 0x108833600] Invalid NAL unit size (22545 > 13889).
[NULL @ 0x108833600] missing picture in access unit with size 13893

이를 이용해서 종료되었음을 알릴 수 있는 방법..? -> 서버 필요 ?

**Comment by hanslelee** [comment]
## 오류 해결
timer를 이용하여 백엔드에서 해당 스트리밍이 릴리즈 되었는지, 진행중인지 확인하는 api를 주기적으로 불러오는 것으로 결정되었습니다.
